# Generated by Django 4.1.5 on 2023-01-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default='profile_pic/default.jpg', upload_to='profile_pic'),
        ),
    ]
